import "./Footer.css";

const Footer = () => {
  return (
    <div className="Footer">
      <div>
        All prompts were generated by the{" "}
        <a
          href="https://en.wikipedia.org/wiki/GPT-3"
          target="_blank"
          rel="noreferrer"
        >
          GPT3 AI
        </a>
        .
      </div>
      <div>
        Musa was made with &lt;3 by{" "}
        <a href="https://github.com/diksown" target="_blank" rel="noreferrer">
          Dikson Santos
        </a>
        .
      </div>
    </div>
  );
};

export default Footer;
