import "./Footer.css";

const Footer = () => {
  return (
    <div className="Footer">
      <div>All prompts were generated by the GPT3 AI.</div>
      <div>Musa was made with &lt;3 by Dikson Santos.</div>
    </div>
  );
};

export default Footer;
